export let data = [
  {
    id: 1,
    title: 'Сказочное заморское яство',
    taste: 'с фуа-гра',
    available: true,
    amount: '10 порций',
    bonus: 'мышь в подарок',
    result: '',
    weight: '0,5',
    description: 'Печень утки разварная с артишоками.',
  },
  {
    id: 2,
    title: 'Сказочное заморское яство',
    taste: 'с рыбой',
    available: true,
    amount: '40 порций',
    bonus: '2 мыши в подарок',
    result: '',
    weight: 2,
    description: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
  },
  {
    id: 3,
    title: 'Сказочное заморское яство',
    taste: 'с курой',
    available: false,
    amount: '100 порций',
    bonus: '5 мышей в подарок',
    result: 'заказчик доволен',
    weight: 5,
    description: 'Филе из цыплят с трюфелями в бульоне.',
  },
]
